### ISSUE TITLE
Not compatible with piwik 3.0.0

### ISSUE THREAD

**Issue by tehnotronic** [ThaDafinser/Piwik-LdapConnection#3]
This plugin is not compatible with piwik 3.0.0, please update it, this is a great and useful plugin!

**Comment by ThaDafinser** [comment]
Those 3 ***plugins should work now with all with `piwik 3`*** :tada: 

I tried them all local on a fresh installation successfull now, so please test them carefully and provide me some feedback!

# Installation
Download the ZIP from GitHub and install it by hand, see https://piwik.org/faq/plugins/faq_21/

## LdapVisitorInfo (requires both plugins)
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/tree/feature/piwik3
https://github.com/ThaDafinser/Piwik-LdapConnection/tree/feature/piwik3

## Ip2Hostname
https://github.com/ThaDafinser/Piwik-Ip2Hostname/tree/feature/piwik3

## IntranetGeoIp
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/tree/feature/piwik3

**Comment by ThaDafinser** [comment]
Just released the package - should be soon available over the marketplace!
